### ISSUE TITLE
Scraping nm0325717 results in null pointer

### ISSUE THREAD

**Issue by Raveen87** [JnRMnT/JMovies.IMDb#13]
**Describe the bug**
When scraping [William Golding, nm0325717](https://www.imdb.com/name/nm0325717/) the library encounters a null pointer and crashes.
This happens in the latest released version, 1.8.3.

**To Reproduce**
```
var dataProvider = new IMDbScraperDataProvider();
var person = await dataProvider.GetPersonAsync(325717);
```

**Stack trace**
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at JMovies.IMDb.Helpers.People.PersonPageHelper.Parse(Person person, HtmlNode documentNode, PersonDataFetchSettings settings)
   at JMovies.IMDb.Providers.IMDbScraperDataProvider.<>c__DisplayClass2_0.<AsyncGetPerson>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at JMovies.IMDb.Providers.IMDbScraperDataProvider.GetPersonAsync(Int64 id, PersonDataFetchSettings settings)
```

**Additional information**
I tried to specify `PersonDataFetchSettings` with various settings, but that had no effect.

**Comment by JnRMnT** [comment]
This is now fixed with version 1.8.4
